/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package start;

import config.config;
import java.awt.Color;
import start.loginform;

/**
 *
 * @author User
 */

public class confirm_logout extends javax.swing.JFrame {
    
private javax.swing.JFrame previousFrame;

    /**
     * Creates new form confirm_logout
     */
    public confirm_logout(javax.swing.JFrame previousFrame) {
        this.previousFrame = previousFrame;
        initComponents();
    }
    
    Color logoff_color = new Color(192, 57, 43);
    Color logoff_color2 = new Color(255,76,48);
    Color yes_color = new Color(255,255,255);
    Color yes_color2 = new Color(153,153,153);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        no = new javax.swing.JPanel();
        logoff_txt = new javax.swing.JLabel();
        yes = new javax.swing.JPanel();
        logoff_txt1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 59, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        no.setBackground(new java.awt.Color(242, 38, 19));
        no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noMouseExited(evt);
            }
        });

        logoff_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoff_txt.setForeground(new java.awt.Color(255, 255, 255));
        logoff_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoff_txt.setText("No");

        javax.swing.GroupLayout noLayout = new javax.swing.GroupLayout(no);
        no.setLayout(noLayout);
        noLayout.setHorizontalGroup(
            noLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoff_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        noLayout.setVerticalGroup(
            noLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoff_txt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        yes.setBackground(new java.awt.Color(255, 255, 255));
        yes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yesMouseExited(evt);
            }
        });

        logoff_txt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoff_txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoff_txt1.setText("Yes");

        javax.swing.GroupLayout yesLayout = new javax.swing.GroupLayout(yes);
        yes.setLayout(yesLayout);
        yesLayout.setHorizontalGroup(
            yesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoff_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        yesLayout.setVerticalGroup(
            yesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoff_txt1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("You want to Log out?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseClicked
        if (previousFrame != null) {
        previousFrame.setVisible(true);
    }
        this.dispose();
    }//GEN-LAST:event_noMouseClicked

    private void noMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseEntered
        no.setBackground(logoff_color);
    }//GEN-LAST:event_noMouseEntered

    private void noMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseExited
        no.setBackground(logoff_color2);
    }//GEN-LAST:event_noMouseExited

    private void yesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseClicked
        config.Session.clear();
        new loginform().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_yesMouseClicked

    private void yesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseEntered
        yes.setBackground(yes_color2);
    }//GEN-LAST:event_yesMouseEntered

    private void yesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseExited
        yes.setBackground(yes_color);
    }//GEN-LAST:event_yesMouseExited

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoff_txt;
    private javax.swing.JLabel logoff_txt1;
    private javax.swing.JPanel no;
    private javax.swing.JPanel yes;
    // End of variables declaration//GEN-END:variables
}
