package start;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;


/**
 *
 * @author User
 */
public class landing extends javax.swing.JFrame {

    /**
     * Creates new form landing
     */
    public landing() {
        initComponents();
    }
    
    Color signupcolor = new Color(51,153,255);
    Color signupcolor2 = new Color(51,204,255);
    Color logincolor = new Color(102,204,0);
    Color logincolor2 = new Color(102,225,0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imagebackground = new javax.swing.JPanel();
        landing_image = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        landing_logo = new javax.swing.JLabel();
        signup = new javax.swing.JPanel();
        lnd_reg = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        lnd_login1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(null);

        screen.setBackground(new java.awt.Color(174, 221, 247));
        screen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("your diagnosis history in the application so you won't have to worry about");
        screen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 540, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("A website for patients and doctors to keep track of your diagnosis");
        screen.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 490, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setText("________________________________________________________________________________");
        screen.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 580, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("history you got from your doctor. This application helps you by storing");
        screen.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 530, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel6.setText("Patient Diagnosis Records");
        screen.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setText("Welcome Patients!");
        screen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 40));

        imagebackground.setBackground(new java.awt.Color(255, 255, 255));
        imagebackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        landing_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor1.png"))); // NOI18N
        imagebackground.add(landing_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 330));

        screen.add(imagebackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 330, 350));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel7.setText("Already have an account.");
        screen.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 170, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setText("loosing your diagnosis papers you receive from you doctor.");
        screen.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 440, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel10.setText("Want to Register an account?");
        screen.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 200, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel11.setText("________________________________________________________________________________");
        screen.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 580, 20));

        landing_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landing_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo small.jpg"))); // NOI18N
        screen.add(landing_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 50));

        signup.setBackground(new java.awt.Color(51, 153, 255));
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMouseExited(evt);
            }
        });
        signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lnd_reg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lnd_reg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnd_reg.setText("Register");
        signup.add(lnd_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 30));

        screen.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 180, 50));

        login.setBackground(new java.awt.Color(102, 204, 0));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lnd_login1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lnd_login1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnd_login1.setText("Login");
        login.add(lnd_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, 30));

        screen.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 180, 50));

        jLabel13.setText("jLabel13");
        screen.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
        signup.setBackground(signupcolor2);
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseExited
        signup.setBackground(signupcolor);
    }//GEN-LAST:event_signupMouseExited

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(logincolor2);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(logincolor);
    }//GEN-LAST:event_loginMouseExited

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        registerform rgf = new registerform();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_signupMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        loginform lgf = new loginform();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imagebackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel landing_image;
    private javax.swing.JLabel landing_logo;
    private javax.swing.JLabel lnd_login1;
    private javax.swing.JLabel lnd_reg;
    private javax.swing.JPanel login;
    private javax.swing.JPanel screen;
    private javax.swing.JPanel signup;
    // End of variables declaration//GEN-END:variables
}
