package start;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import admin.adminDashboard;
import nurse.nurseDashboard;
import users.usersDashboard;
import config.config;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
    }
    
    Color logoff_color = new Color(192, 57, 43);
    Color logoff_color2 = new Color(255,76,48);
    Color login_color = new Color(46,204,113);
    Color login_color2 = new Color(22, 160, 133);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lgf_rgf_no = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login_uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        lgn = new javax.swing.JLabel();
        login_pass = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        login_image = new javax.swing.JLabel();
        logoff = new javax.swing.JPanel();
        logoff_txt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(4, 59, 92));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Diagnosis Records");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 240, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("_____________________________________________________________________________________________");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 660, 20));

        lgf_rgf_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lgf_rgf_no.setForeground(new java.awt.Color(255, 255, 255));
        lgf_rgf_no.setText("Click here to creat a new Account");
        lgf_rgf_no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lgf_rgf_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgf_rgf_noMouseClicked(evt);
            }
        });
        jPanel2.add(lgf_rgf_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 280, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        login_uname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(login_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 170, -1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 260, -1));

        login.setBackground(new java.awt.Color(46, 204, 113));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        lgn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lgn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgn.setText("Login");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lgn)
                .addContainerGap())
        );

        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 140, -1));

        login_pass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel2.add(login_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 170, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Username:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        login_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo login.jpg"))); // NOI18N
        jPanel2.add(login_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 240));

        logoff.setBackground(new java.awt.Color(255, 76, 48));
        logoff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoffMouseExited(evt);
            }
        });

        logoff_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoff_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoff_txt.setText("Log Off");

        javax.swing.GroupLayout logoffLayout = new javax.swing.GroupLayout(logoff);
        logoff.setLayout(logoffLayout);
        logoffLayout.setHorizontalGroup(
            logoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoff_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoffLayout.setVerticalGroup(
            logoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoff_txt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(logoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 670, 360));

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(login_color2);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(login_color);
    }//GEN-LAST:event_loginMouseExited

    private void lgf_rgf_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgf_rgf_noMouseClicked
        registerform rgf = new registerform();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lgf_rgf_noMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        config con = new config();
        String result = con.loginWithValidation(login_uname.getText(), login_pass.getText());

        switch(result) {
            case "User does not exist":
                JOptionPane.showMessageDialog(null, "User does not exist!");
                break;
            case "Invalid password":
                JOptionPane.showMessageDialog(null, "Invalid password!");
                break;
            case "Deactivated":
                JOptionPane.showMessageDialog(null, "Your Account Has Been Deactivated!");
                break;
            case "Admin":
                JOptionPane.showMessageDialog(null, "Login Success");
                new adminDashboard().setVisible(true);
                this.dispose();
                break;
            case "Staff":
                JOptionPane.showMessageDialog(null, "Login Success");
                new nurseDashboard().setVisible(true);
                this.dispose();
                break;
            case "User":
                JOptionPane.showMessageDialog(null, "Login Success");
                new usersDashboard().setVisible(true);
                this.dispose();
                break;
            default:
                JOptionPane.showMessageDialog(null, "Something went wrong!");
                break;
        }
    }//GEN-LAST:event_loginMouseClicked

    private void logoffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoffMouseClicked
        dispose();
    }//GEN-LAST:event_logoffMouseClicked

    private void logoffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoffMouseEntered
        logoff.setBackground(logoff_color);
    }//GEN-LAST:event_logoffMouseEntered

    private void logoffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoffMouseExited
        logoff.setBackground(logoff_color2);
    }//GEN-LAST:event_logoffMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lgf_rgf_no;
    private javax.swing.JLabel lgn;
    private javax.swing.JPanel login;
    private javax.swing.JLabel login_image;
    private javax.swing.JPasswordField login_pass;
    private javax.swing.JTextField login_uname;
    private javax.swing.JPanel logoff;
    private javax.swing.JLabel logoff_txt;
    // End of variables declaration//GEN-END:variables
}
