package start;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import start.loginform;
import start.landing;
import config.config;
import java.awt.Color;
import javax.swing.ButtonGroup;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class registerform extends javax.swing.JFrame {

    /**
     * Creates new form registerform
     */
    public registerform() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(male_btn);
        bg.add(female_btn);

    }
    
    Color register_back_color = new Color(192, 57, 43);
    Color register_back_color2 = new Color(255,76,48);
    Color register_color = new Color(46,204,113);
    Color register_color2 = new Color(22, 160, 133);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        occupation = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        bdate = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        register = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        register_back = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rgf_login_yes = new javax.swing.JLabel();
        confirm_pass = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        mname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        male_btn = new javax.swing.JRadioButton();
        female_btn = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("REGISTRATION FORM");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        jPanel2.setBackground(new java.awt.Color(4, 59, 92));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Middle Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Age:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sex:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Birth Date:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Occupation:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Diagnosis Records");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 240, -1));

        occupation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 170, -1));

        fname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 170, -1));

        lname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 170, -1));

        age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 170, -1));

        bdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 170, -1));

        status.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 170, -1));

        phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 170, -1));

        address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 170, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Username:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 170, -1));

        username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 170, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("____________________________________________________________________________________________________________________________");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 880, 20));

        register.setBackground(new java.awt.Color(46, 204, 113));
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Done");

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 140, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Phone Number:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        register_back.setBackground(new java.awt.Color(255, 76, 48));
        register_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_backMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cancel");

        javax.swing.GroupLayout register_backLayout = new javax.swing.GroupLayout(register_back);
        register_back.setLayout(register_backLayout);
        register_backLayout.setHorizontalGroup(
            register_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        register_backLayout.setVerticalGroup(
            register_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, register_backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(register_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Password:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        rgf_login_yes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rgf_login_yes.setForeground(new java.awt.Color(255, 255, 255));
        rgf_login_yes.setText("Already have an Account? Click here to Login");
        rgf_login_yes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rgf_login_yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rgf_login_yesMouseClicked(evt);
            }
        });
        jPanel2.add(rgf_login_yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 360, -1));

        confirm_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_passActionPerformed(evt);
            }
        });
        jPanel2.add(confirm_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 170, -1));
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 170, -1));

        mname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 170, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Last Name:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        male_btn.setBackground(new java.awt.Color(0, 0, 0));
        male_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        male_btn.setForeground(new java.awt.Color(255, 255, 255));
        male_btn.setText("Male");
        male_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_btnActionPerformed(evt);
            }
        });
        jPanel2.add(male_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 70, -1));

        female_btn.setBackground(new java.awt.Color(0, 0, 0));
        female_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        female_btn.setForeground(new java.awt.Color(255, 255, 255));
        female_btn.setText("Female");
        female_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_btnActionPerformed(evt);
            }
        });
        jPanel2.add(female_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Please fill out the form to sucessfully register your records for doctors to use as reference to you, the patient. This form helps doctors");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 840, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("to know who their patient is and if the need arises can be contacted by both the patient and doctors for any medical advices.");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 830, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 860, 60));

        jLabel26.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("____________________________________________________________________________________________________________________________");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 880, 20));

        jLabel27.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("____________________________________________________________________________________________________________________________");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 880, 20));

        jLabel28.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("____________________________________________________________________________________________________________________________");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 880, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        register.setBackground(register_color2);
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        register.setBackground(register_color);
    }//GEN-LAST:event_registerMouseExited

    private void register_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_backMouseEntered
        register_back.setBackground(register_back_color);
    }//GEN-LAST:event_register_backMouseEntered

    private void register_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_backMouseExited
        register_back.setBackground(register_back_color2);
    }//GEN-LAST:event_register_backMouseExited

    private void rgf_login_yesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgf_login_yesMouseClicked
        loginform lgf = new loginform();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_rgf_login_yesMouseClicked

    private void register_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_backMouseClicked
        landing lnd = new landing();
        lnd.setVisible(true);
        lnd.pack();
        lnd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_register_backMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        
        // Check if any field is empty
        if (username.getText().isEmpty() ||
            password.getText().isEmpty() ||
            confirm_pass.getText().isEmpty() ||
            fname.getText().isEmpty() ||
            lname.getText().isEmpty() ||
            mname.getText().isEmpty() ||
            email.getText().isEmpty() ||
            age.getText().isEmpty() ||
            bdate.getText().isEmpty() ||
            status.getText().isEmpty() ||
            phone.getText().isEmpty() ||
            address.getText().isEmpty() ||
            occupation.getText().isEmpty() ||
            (!male_btn.isSelected() && !female_btn.isSelected())) {

            JOptionPane.showMessageDialog(this,
                    "Please fill out the form before pressing \"Done\"",
                    "Incomplete Form",
                    JOptionPane.WARNING_MESSAGE);
            return; // Stop execution so nothing is added
        }
        
        config con = new config();
        
        String gender = "";
        if (male_btn.isSelected()) {
            gender = "Male";
        } else if (female_btn.isSelected()) {
            gender = "Female";
        }
        
            // Check if username already exists
        boolean usernameTaken = false;
        String checkSql = "SELECT * FROM tbl_accounts WHERE u_name=?";
        try (Connection conn = config.connectDB();
             PreparedStatement ps = conn.prepareStatement(checkSql)) {
            ps.setString(1, username.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                usernameTaken = true;
            }
        } catch (Exception e) {
            System.out.println("Error checking username: " + e.getMessage());
        }

        if (usernameTaken) {
            JOptionPane.showMessageDialog(this, "Username Already Taken", "Error", JOptionPane.ERROR_MESSAGE);
            username.setText("");   // Clear the text field
            username.requestFocus(); // Focus back to the username field
            return; // Stop execution so no record is added
        }
        
        String sql = "INSERT INTO tbl_accounts (u_name, u_pass, confirm_pass, f_name, l_name, m_name, email, sex, age, b_date, status, phone, address, occupation, role, account_status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        con.addRecord(sql, username.getText(), password.getText(), confirm_pass.getText(), fname.getText(), lname.getText(), mname.getText(), email.getText(), gender, age.getText(), bdate.getText(), status.getText(), phone.getText(), address.getText(), occupation.getText(), "User", "Active");
        //registerform rgf = new registerform(); 
        loginform lgf = new loginform();
        lgf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerMouseClicked

    private void confirm_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_passActionPerformed

    private void female_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_btnActionPerformed

    private void male_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField bdate;
    private javax.swing.JPasswordField confirm_pass;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female_btn;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male_btn;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField occupation;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JPanel register;
    private javax.swing.JPanel register_back;
    private javax.swing.JLabel rgf_login_yes;
    private javax.swing.JTextField status;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
