package start;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import start.loginform;
import start.landing;
import config.config;
import java.awt.Color;
import javax.swing.ButtonGroup;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class registerform extends javax.swing.JFrame {

    /**
     * Creates new form registerform
     */
    public registerform() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(male_btn);
        bg.add(female_btn);

    }
    
    Color register_back_color = new Color(192, 57, 43);
    Color register_back_color2 = new Color(255,76,48);
    Color register_color = new Color(46,204,113);
    Color register_color2 = new Color(22, 160, 133);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        register = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        register_back = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rgf_login_yes = new javax.swing.JLabel();
        confirm_pass = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        male_btn = new javax.swing.JRadioButton();
        female_btn = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("REGISTRATION FORM");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel2.setBackground(new java.awt.Color(4, 59, 92));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Diagnosis Records");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Username:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("____________________________________________________");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 370, 20));

        register.setBackground(new java.awt.Color(46, 204, 113));
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Done");

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 140, -1));

        register_back.setBackground(new java.awt.Color(255, 76, 48));
        register_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_backMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cancel");

        javax.swing.GroupLayout register_backLayout = new javax.swing.GroupLayout(register_back);
        register_back.setLayout(register_backLayout);
        register_backLayout.setHorizontalGroup(
            register_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        register_backLayout.setVerticalGroup(
            register_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, register_backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(register_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Password:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        rgf_login_yes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rgf_login_yes.setForeground(new java.awt.Color(255, 255, 255));
        rgf_login_yes.setText("Already have an Account? Click here to Login");
        rgf_login_yes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rgf_login_yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rgf_login_yesMouseClicked(evt);
            }
        });
        jPanel2.add(rgf_login_yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 360, -1));

        confirm_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_passActionPerformed(evt);
            }
        });
        jPanel2.add(confirm_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 170, -1));
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 170, -1));

        male_btn.setBackground(new java.awt.Color(0, 0, 0));
        male_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        male_btn.setForeground(new java.awt.Color(255, 255, 255));
        male_btn.setText("Male");
        male_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_btnActionPerformed(evt);
            }
        });
        jPanel2.add(male_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 70, -1));

        female_btn.setBackground(new java.awt.Color(0, 0, 0));
        female_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        female_btn.setForeground(new java.awt.Color(255, 255, 255));
        female_btn.setText("Female");
        female_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_btnActionPerformed(evt);
            }
        });
        jPanel2.add(female_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("____________________________________________________");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 370, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("____________________________________________________");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 370, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        register.setBackground(register_color2);
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        register.setBackground(register_color);
    }//GEN-LAST:event_registerMouseExited

    private void register_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_backMouseEntered
        register_back.setBackground(register_back_color);
    }//GEN-LAST:event_register_backMouseEntered

    private void register_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_backMouseExited
        register_back.setBackground(register_back_color2);
    }//GEN-LAST:event_register_backMouseExited

    private void rgf_login_yesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgf_login_yesMouseClicked
        loginform lgf = new loginform();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_rgf_login_yesMouseClicked

    private void register_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_backMouseClicked
        landing lnd = new landing();
        lnd.setVisible(true);
        lnd.pack();
        lnd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_register_backMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        
        // Check if any field is empty
        // ✅ NEW — short registration validation only
        if (username.getText().isEmpty() ||
            password.getText().isEmpty() ||
            confirm_pass.getText().isEmpty() ||
            (!male_btn.isSelected() && !female_btn.isSelected())) {

            JOptionPane.showMessageDialog(this,
                "Please complete basic registration fields",
                "Incomplete Form",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        config con = new config();
        
        String gender = "";
        if (male_btn.isSelected()) {
            gender = "Male";
        } else if (female_btn.isSelected()) {
            gender = "Female";
        }
        
            // Check if username already exists
        boolean usernameTaken = false;
        String checkSql = "SELECT * FROM tbl_accounts WHERE u_name=?";
        try (Connection conn = config.connectDB();
             PreparedStatement ps = conn.prepareStatement(checkSql)) {
            ps.setString(1, username.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                usernameTaken = true;
            }
        } catch (Exception e) {
            System.out.println("Error checking username: " + e.getMessage());
        }

        if (usernameTaken) {
            JOptionPane.showMessageDialog(this, "Username Already Taken", "Error", JOptionPane.ERROR_MESSAGE);
            username.setText("");   // Clear the text field
            username.requestFocus(); // Focus back to the username field
            return; // Stop execution so no record is added
        }
        
        String sql = "INSERT INTO tbl_accounts" + "(u_name, u_pass, confirm_pass, sex, role, account_status)" + "VALUES (?, ?, ?, ?, ?, ?)";
        con.addRecord(sql, username.getText(), password.getText(), confirm_pass.getText(), gender, "User", "Active");
        //registerform rgf = new registerform(); 
        loginform lgf = new loginform();
        lgf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerMouseClicked

    private void confirm_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_passActionPerformed

    private void female_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_btnActionPerformed

    private void male_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirm_pass;
    private javax.swing.JRadioButton female_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male_btn;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel register;
    private javax.swing.JPanel register_back;
    private javax.swing.JLabel rgf_login_yes;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
