/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users;

import config.config;
import java.awt.Color;
import start.confirm_logout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import start.continue_register;

/**
 *
 * @author User
 */
public class usersProfile extends javax.swing.JFrame {

    /**
     * Creates new form usersProfile
     */
    public usersProfile() {
        initComponents();
        u_continue.setVisible(false);
        loadUserProfile();
    }
    
    Color logout_color = new Color(192, 57, 43);
    Color logout_color2 = new Color(255,76,48);
    Color back_color = new Color(51,153,255);
    Color back_color2 = new Color(0,204,204);
    Color u_continue_color = new Color(46,204,113);
    Color u_continue_color2 = new Color(22, 160, 133);
    
    private String showNA(String value) {
    if (value == null || value.trim().isEmpty()) {
        return "N/A";
    }
    return value;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        profile_sex = new javax.swing.JLabel();
        user_logout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        patient_num = new javax.swing.JLabel();
        profile_name1 = new javax.swing.JLabel();
        profile_age = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        profile_email = new javax.swing.JLabel();
        profile_phone = new javax.swing.JLabel();
        u_continue = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        user_back = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 59, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 181, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PATIENT DIAGNOSIS RECORDS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(669, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 70));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pfp.png"))); // NOI18N
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, 100));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("_____________________");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 40));

        profile_sex.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profile_sex.setText("sex");
        jPanel7.add(profile_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, 40));

        user_logout.setBackground(new java.awt.Color(255, 76, 48));
        user_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user_logoutMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Log Out");

        javax.swing.GroupLayout user_logoutLayout = new javax.swing.GroupLayout(user_logout);
        user_logout.setLayout(user_logoutLayout);
        user_logoutLayout.setHorizontalGroup(
            user_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_logoutLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        user_logoutLayout.setVerticalGroup(
            user_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(user_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        patient_num.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patient_num.setText("patient number");
        jPanel7.add(patient_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 270, 40));

        profile_name1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profile_name1.setText("name");
        jPanel7.add(profile_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 40));

        profile_age.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profile_age.setText("age");
        jPanel7.add(profile_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 270, 40));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 420));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile_email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profile_email.setText("Email:");
        jPanel5.add(profile_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 40));

        profile_phone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profile_phone.setText("Phone Number:");
        jPanel5.add(profile_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, 40));

        u_continue.setBackground(new java.awt.Color(46, 204, 113));
        u_continue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u_continueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                u_continueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                u_continueMouseExited(evt);
            }
        });
        u_continue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Continue to Register ?");
        u_continue.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel5.add(u_continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 220, 60));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 650, 370));

        user_back.setBackground(new java.awt.Color(51, 153, 255));
        user_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user_backMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("< Back");

        javax.swing.GroupLayout user_backLayout = new javax.swing.GroupLayout(user_back);
        user_back.setLayout(user_backLayout);
        user_backLayout.setHorizontalGroup(
            user_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_backLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        user_backLayout.setVerticalGroup(
            user_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(user_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1020, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1060, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void user_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_logoutMouseEntered
        user_logout.setBackground(logout_color);
    }//GEN-LAST:event_user_logoutMouseEntered

    private void user_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_backMouseClicked
        new usersDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_user_backMouseClicked

    private void user_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_logoutMouseClicked
        new confirm_logout(this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_user_logoutMouseClicked

    private void user_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_logoutMouseExited
        user_logout.setBackground(logout_color2);
    }//GEN-LAST:event_user_logoutMouseExited

    private void user_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_backMouseEntered
        user_back.setBackground(back_color2);
    }//GEN-LAST:event_user_backMouseEntered

    private void user_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_backMouseExited
        user_back.setBackground(back_color);
    }//GEN-LAST:event_user_backMouseExited

    private void u_continueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_continueMouseClicked
        new continue_register(config.Session.userId, this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_u_continueMouseClicked

    private void u_continueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_continueMouseEntered
        u_continue.setBackground(u_continue_color2);
    }//GEN-LAST:event_u_continueMouseEntered

    private void u_continueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_continueMouseExited
        u_continue.setBackground(u_continue_color);
    }//GEN-LAST:event_u_continueMouseExited

    /**
     * @param args the command line arguments
     */
    private void loadUserProfile() {

        config con = new config();

        String sql = "SELECT * FROM tbl_accounts WHERE u_id=?";

        try (Connection conn = config.connectDB();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, config.Session.userId);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {

                patient_num.setText("Patient ID: " + rs.getInt("u_id"));
                
                String fname = showNA(rs.getString("f_name"));
                String mname = rs.getString("m_name");
                String lname = showNA(rs.getString("l_name"));

                String fullName = fname + " "
                        + (mname == null || mname.trim().isEmpty() ? "" : mname + " ")
                        + lname;
                
                profile_name1.setText("Name: " + fullName);
                profile_age.setText("Age: " + showNA(rs.getString("age")));
                profile_sex.setText("Sex: " + showNA(rs.getString("sex")));
                profile_email.setText("Email: " + showNA(rs.getString("email")));
                profile_phone.setText("Phone: " + showNA(rs.getString("phone")));
                
                boolean incomplete =
                    rs.getString("age") == null || rs.getString("age").trim().isEmpty() ||
                    rs.getString("sex") == null || rs.getString("sex").trim().isEmpty() ||
                    rs.getString("phone") == null || rs.getString("phone").trim().isEmpty(); //||
                    //rs.getString("m_name") == null || rs.getString("m_name").trim().isEmpty();
                    
                u_continue.setVisible(incomplete);


            } else {
                patient_num.setText("Patient ID: N/A");
                profile_name1.setText("Name: N/A");
                profile_age.setText("Age: N/A");
                profile_sex.setText("Sex: N/A");
                profile_email.setText("Email: N/A");
                profile_phone.setText("Phone: N/A");
                
                u_continue.setVisible(true);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usersProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel patient_num;
    private javax.swing.JLabel profile_age;
    private javax.swing.JLabel profile_email;
    private javax.swing.JLabel profile_name1;
    private javax.swing.JLabel profile_phone;
    private javax.swing.JLabel profile_sex;
    private javax.swing.JPanel u_continue;
    private javax.swing.JPanel user_back;
    private javax.swing.JPanel user_logout;
    // End of variables declaration//GEN-END:variables
}
