/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.config;
import java.awt.Color;
import start.confirm_logout;
//import start.loginform;


/**
 *
 * @author USER5
 */
public class adminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public adminDashboard() {
        initComponents();
        
        String lastName = "Anonymous";
        if (config.Session.lastName != null && !config.Session.lastName.trim().isEmpty()) {
            lastName = config.Session.lastName;
        }

        greetings.setText("Greetings Administrator " + lastName);

    }
    
    Color logout_color = new Color(192, 57, 43);
    Color logout_color2 = new Color(255,76,48);
    Color users_color = new Color(255,255,255);
    Color users_color2 = new Color(204,204,204);
    
    
    //void getUsersData(){
    
        //config con = new config();
        //String sql = "SELECT * FROM tbl_accounts";
        //con.displayData(sql, uTable);
        
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        home_btn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        users_btn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ad_lgo_pnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ad_profile = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        greetings = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        home_btn.setBackground(new java.awt.Color(204, 204, 204));
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_btnMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOME");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout home_btnLayout = new javax.swing.GroupLayout(home_btn);
        home_btn.setLayout(home_btnLayout);
        home_btnLayout.setHorizontalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_btnLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        home_btnLayout.setVerticalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(home_btn);
        home_btn.setBounds(0, 70, 190, 52);

        users_btn.setBackground(new java.awt.Color(255, 255, 255));
        users_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                users_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                users_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                users_btnMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ALL USERS");

        javax.swing.GroupLayout users_btnLayout = new javax.swing.GroupLayout(users_btn);
        users_btn.setLayout(users_btnLayout);
        users_btnLayout.setHorizontalGroup(
            users_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(users_btnLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        users_btnLayout.setVerticalGroup(
            users_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(users_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(users_btn);
        users_btn.setBounds(0, 120, 190, 52);

        jPanel4.setBackground(new java.awt.Color(8, 97, 150));
        jPanel4.setLayout(null);

        ad_lgo_pnl.setBackground(new java.awt.Color(255, 76, 48));
        ad_lgo_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ad_lgo_pnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ad_lgo_pnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ad_lgo_pnlMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGOUT");

        javax.swing.GroupLayout ad_lgo_pnlLayout = new javax.swing.GroupLayout(ad_lgo_pnl);
        ad_lgo_pnl.setLayout(ad_lgo_pnlLayout);
        ad_lgo_pnlLayout.setHorizontalGroup(
            ad_lgo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ad_lgo_pnlLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        ad_lgo_pnlLayout.setVerticalGroup(
            ad_lgo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_lgo_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(ad_lgo_pnl);
        ad_lgo_pnl.setBounds(0, 450, 190, 52);

        ad_profile.setBackground(new java.awt.Color(255, 255, 255));
        ad_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ad_profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ad_profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ad_profileMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("YOUR PROFILE");

        javax.swing.GroupLayout ad_profileLayout = new javax.swing.GroupLayout(ad_profile);
        ad_profile.setLayout(ad_profileLayout);
        ad_profileLayout.setHorizontalGroup(
            ad_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_profileLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ad_profileLayout.setVerticalGroup(
            ad_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_profileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(ad_profile);
        ad_profile.setBounds(0, 400, 190, 52);

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("...");

        javax.swing.GroupLayout btn3Layout = new javax.swing.GroupLayout(btn3);
        btn3.setLayout(btn3Layout);
        btn3Layout.setHorizontalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btn3Layout.setVerticalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(btn3);
        btn3.setBounds(0, 100, 190, 52);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 70, 190, 500);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 10, 50, 50);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 570));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADMINISTRATOR'S DASHBOARD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel7)
                .addContainerGap(471, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 930, 70));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pfp.png"))); // NOI18N
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, 100));

        text.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("of the Patients Diagnosis Records System!");
        jPanel7.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 600, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("_________________________________________________________");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 660, 40));

        greetings.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        greetings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetings.setText("...");
        jPanel7.add(greetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 600, 40));

        text1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("Welcome to the Administrator's Dashboard");
        jPanel7.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 600, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("_________________________________________________________");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 660, 40));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 420));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 830, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 870, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ad_lgo_pnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad_lgo_pnlMouseEntered
        ad_lgo_pnl.setBackground(logout_color);
    }//GEN-LAST:event_ad_lgo_pnlMouseEntered

    private void ad_lgo_pnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad_lgo_pnlMouseExited
        ad_lgo_pnl.setBackground(logout_color2);
    }//GEN-LAST:event_ad_lgo_pnlMouseExited

    private void ad_lgo_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad_lgo_pnlMouseClicked
        new confirm_logout(this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ad_lgo_pnlMouseClicked

    private void users_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_btnMouseEntered
        users_btn.setBackground(users_color2);
    }//GEN-LAST:event_users_btnMouseEntered

    private void users_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_btnMouseExited
        users_btn.setBackground(users_color);
    }//GEN-LAST:event_users_btnMouseExited

    private void home_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseEntered
        home_btn.setBackground(users_color);
    }//GEN-LAST:event_home_btnMouseEntered

    private void home_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseExited
        home_btn.setBackground(users_color2);
    }//GEN-LAST:event_home_btnMouseExited

    private void users_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_btnMouseClicked
        new ad_allUsersHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_users_btnMouseClicked

    private void ad_profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad_profileMouseEntered
        ad_profile.setBackground(users_color2);
    }//GEN-LAST:event_ad_profileMouseEntered

    private void ad_profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad_profileMouseExited
        ad_profile.setBackground(users_color);
    }//GEN-LAST:event_ad_profileMouseExited

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
        btn3.setBackground(users_color2);
    }//GEN-LAST:event_btn3MouseEntered

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
        btn3.setBackground(users_color);
    }//GEN-LAST:event_btn3MouseExited

    private void ad_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad_profileMouseClicked
        new ad_profile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ad_profileMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ad_lgo_pnl;
    private javax.swing.JPanel ad_profile;
    private javax.swing.JPanel btn3;
    private javax.swing.JLabel greetings;
    private javax.swing.JPanel home_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text1;
    private javax.swing.JPanel users_btn;
    // End of variables declaration//GEN-END:variables
}
